/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import Modelo.Cola;

/**
 *
 * @author nicolas
 */
public class VentanaProceso extends javax.swing.JFrame {

    private int numero = 0;
    private int llegada;
    private int rafaga;
    private int prioridad;

    private JTable jTableProcesos;
    private JLabel lblInicio;
    private JTextArea txaConsola;
   

    Cola cola;

    /**
     * Creates new form VentanaProceso
     */
    VentanaProceso(JTable jTableProcesos, JTextArea area) {
        this.jTableProcesos = jTableProcesos;
      //  this.lblInicio = lblInicio;
        this.txaConsola = area;
        
        initComponents();
        this.setLocationRelativeTo(null);
        cola = new Cola(area);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroProceso = new javax.swing.JLabel();
        lblRafaga = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtRafaga = new javax.swing.JTextField();
        lblPrioridad = new javax.swing.JLabel();
        txtPrioridad = new javax.swing.JTextField();
        tiempoLlegada = new javax.swing.JTextField();

        setTitle("Datos del proceso");
        setBackground(new java.awt.Color(255, 255, 204));

        lblNumeroProceso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroProceso.setText("Tiempo de Llegada:");

        lblRafaga.setText("Tiempo de ráfaga:");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPrioridad.setText("Prioridad:");

        tiempoLlegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoLlegadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRafaga)
                            .addComponent(lblNumeroProceso)
                            .addComponent(lblPrioridad))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tiempoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRafaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        numero++;
        llegada = Integer.parseInt(tiempoLlegada.getText());
        rafaga = Integer.parseInt(txtRafaga.getText());
        prioridad = Integer.parseInt(txtPrioridad.getText());

        cola.insertar(numero, llegada, rafaga, prioridad);
        cola.cargarTabla(jTableProcesos);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tiempoLlegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoLlegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiempoLlegadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblNumeroProceso;
    private javax.swing.JLabel lblPrioridad;
    private javax.swing.JLabel lblRafaga;
    private javax.swing.JTextField tiempoLlegada;
    private javax.swing.JTextField txtPrioridad;
    private javax.swing.JTextField txtRafaga;
    // End of variables declaration//GEN-END:variables

    public int getNumero() {
        return numero;
    }

    public int getLlegada() {
        return llegada;
    }

    public int getRafaga() {
        return rafaga;
    }

    public Cola getCola() {
        return cola;
    }

    public void setCola(Cola cola) {
        this.cola = cola;
    }

}
