package Vista;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextArea;
import Modelo.Cola;

/**
 *
 * @author nicolas
 */
public class Ventana extends JFrame {

    VentanaProceso vProceso;
    SJF sjf;

    public Ventana() {
        initComponents();

        btnIniciar.setEnabled(false);
        vProceso = new VentanaProceso(jTableProcesos, txaConsola);
        pack();
    }

    public JTable getjTable1() {
        return tblGannt;
    }

    public void setjTable1(JTable jTable1) {
        this.tblGannt = jTable1;
    }

    public JTable getjTableProcesos() {
        return jTableProcesos;
    }

    public void setjTableProcesos(JTable jTable1) {
        this.tblGannt = jTableProcesos;
    }

    public JLabel getTiempo_real() {
        return tiempo_real;
    }

    public void setTiempo_real(JLabel tiempo_real) {
        this.tiempo_real = tiempo_real;
    }

    public JLabel getCpu_nuevo() {
        return cpu_nuevo1;
    }

    public void setCpu_nuevo(JLabel cpu_nuevo) {
        this.cpu_nuevo1 = cpu_nuevo;
    }

    public JTextArea getTexto_diagrama() {
        return texto_diagrama;
    }

    public void setTexto_diagrama(JTextArea texto_diagrama) {
        this.texto_diagrama = texto_diagrama;
    }

    public JLabel getProcesos_en_ejecucion() {
        return procesos_en_ejecucion;
    }

    public void setProcesos_en_ejecucion(JLabel procesos_en_ejecucion) {
        this.procesos_en_ejecucion = procesos_en_ejecucion;
    }

    public JTextArea getTexto_listos() {
        return texto_listos;
    }

    public void setTexto_listos(JTextArea texto_listos) {
        this.texto_listos = texto_listos;
    }

    public JLabel getTiempo_cpu() {
        return tiempo_cpu;
    }

    public void setTiempo_cpu(JLabel tiempo_cpu) {
        this.tiempo_cpu = tiempo_cpu;
    }

    public JLabel getTotal_listos() {
        return total_listos;
    }

    public void setTotal_listos(JLabel total_listos) {
        this.total_listos = total_listos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelTodo = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();

        procesos_en_ejecucion = new javax.swing.JLabel();
        total_listos = new javax.swing.JLabel();
        tiempo_real = new javax.swing.JLabel();
        txaConsola = new JTextArea();
        texto_diagrama = new javax.swing.JTextArea();
        PanelGantt = new javax.swing.JScrollPane();
        tblGannt = new javax.swing.JTable();
        PanelTabla = new javax.swing.JScrollPane();
        jTableProcesos = new javax.swing.JTable();
        cpu_nuevo1 = new javax.swing.JLabel();
        tiempo_cpu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_listos = new javax.swing.JTextArea();
        btnInsertar = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       PanelTodo.setLayout(null);



        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar(evt);
            }
        });
        PanelTodo.add(btnIniciar);
        btnIniciar.setBounds(220, 220, 150, 30);

        btnInsertar.setText("Agregar Proceso");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar(evt);
            }
        });
        PanelTodo.add(btnInsertar);
        btnInsertar.setBounds(20, 220, 150, 30);

        tiempo_real.setText("0");

        PanelGantt.setToolTipText("");

        tblGannt.setAutoCreateRowSorter(true);
        tblGannt.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"2", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"3", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"4", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"5", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"6", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"7", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"8", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"9", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"10", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                },
                new String[]{
                    "", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50"}
        ));
        tblGannt.setPreferredSize(new java.awt.Dimension(960, 160));
        PanelGantt.setViewportView(tblGannt);

        PanelTodo.add(PanelGantt);
        PanelGantt.setBounds(1, 270, 965, 185);


        jTableProcesos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}

                },
                new String[]{
                    "Proceso", "T. Llegada", "T. Ráfaga", "T. Comienzo", "T. Final", "T. Retorno", "T. Espera", "Prioridad"
                }
        ));

        jTableProcesos.setEnabled(false);
        PanelTabla.setViewportView(jTableProcesos);

        PanelTodo.add(PanelTabla);
        PanelTabla.setBounds(5, 20, 580, 185);

        texto_listos.setBackground(new java.awt.Color(0, 0, 0));
        texto_listos.setColumns(20);
        texto_listos.setForeground(new java.awt.Color(255, 255, 255));
        texto_listos.setRows(5);
        jScrollPane1.setViewportView(texto_listos);

        PanelTodo.add(jScrollPane1);
        jScrollPane1.setBounds(20, 540, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

    }// </editor-fold>                        


    private void btnIniciar(java.awt.event.ActionEvent evt) {
        Cola cola = new Cola(txaConsola);
        cola = vProceso.getCola();
        sjf = new SJF(cola, this);
        sjf.start();
        btnIniciar.setEnabled(false);
    }

    private void btnInsertar(java.awt.event.ActionEvent evt) {
        vProceso.setVisible(true);
        btnIniciar.setEnabled(true);
    }

    // Variables declaration - do not modify  
    private JTextArea txaConsola;
    private javax.swing.JLabel cpu_nuevo1;
    private javax.swing.JButton btnIniciar;

    private javax.swing.JPanel PanelTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane PanelTabla;
    private javax.swing.JScrollPane PanelGantt;
    private javax.swing.JTable tblGannt;
    private javax.swing.JTable jTableProcesos;
    private javax.swing.JLabel procesos_en_ejecucion;
    private javax.swing.JTextArea texto_diagrama;
    private javax.swing.JTextArea texto_listos;
    private javax.swing.JLabel tiempo_cpu;
    private javax.swing.JLabel tiempo_real;
     private javax.swing.JLabel total_listos;
    private javax.swing.JButton btnInsertar;
    // End of variables declaration  

    public JTextArea getTxaConsola() {
        return txaConsola;
    }

    public void setTxaConsola(JTextArea txaConsola) {
        this.txaConsola = txaConsola;
    }
    
    

}
