package Vista;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import Prioridad.Cola;

/**
 *
 * @author Mafe
 */
public class Ventana extends JFrame {

    VentanaProceso vProceso;
    SJF sjf;

    public Ventana() {
        initComponents();

        btnIniciar.setEnabled(false);
        btnPausar.setEnabled(false);
        vProceso = new VentanaProceso(jTableProcesos, tiempo_real, txaConsola);
        pack();
    }

    public JTable getjTable1() {
        return tblGannt;
    }

    public void setjTable1(JTable jTable1) {
        this.tblGannt = jTable1;
    }

    public JTable getjTableProcesos() {
        return jTableProcesos;
    }

    public void setjTableProcesos(JTable jTable1) {
        this.tblGannt = jTableProcesos;
    }

    public JLabel getTiempo_real() {
        return tiempo_real;
    }

    public void setTiempo_real(JLabel tiempo_real) {
        this.tiempo_real = tiempo_real;
    }

    public JLabel getCpu_nuevo() {
        return cpu_nuevo1;
    }

    public void setCpu_nuevo(JLabel cpu_nuevo) {
        this.cpu_nuevo1 = cpu_nuevo;
    }

    public JTextArea getTexto_diagrama() {
        return texto_diagrama;
    }

    public void setTexto_diagrama(JTextArea texto_diagrama) {
        this.texto_diagrama = texto_diagrama;
    }

    public JLabel getProcesos_en_ejecucion() {
        return procesos_en_ejecucion;
    }

    public void setProcesos_en_ejecucion(JLabel procesos_en_ejecucion) {
        this.procesos_en_ejecucion = procesos_en_ejecucion;
    }

    public JTextArea getTexto_listos() {
        return texto_listos;
    }

    public void setTexto_listos(JTextArea texto_listos) {
        this.texto_listos = texto_listos;
    }

    public JLabel getTiempo_cpu() {
        return tiempo_cpu;
    }

    public void setTiempo_cpu(JLabel tiempo_cpu) {
        this.tiempo_cpu = tiempo_cpu;
    }

    public JLabel getTotal_listos() {
        return total_listos;
    }

    public void setTotal_listos(JLabel total_listos) {
        this.total_listos = total_listos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlArriba = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        btnPausar = new javax.swing.JButton();

        jPanel2 = new javax.swing.JPanel();
        lblNumeroProcesos = new javax.swing.JLabel();
        procesos_en_ejecucion = new javax.swing.JLabel();
        total_listos = new javax.swing.JLabel();

        lblEnEjecucion = new javax.swing.JLabel();
        tiempo_real = new javax.swing.JLabel();
        txaConsola = new JTextArea();
        lblTiempoTotal = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        lblFinalizados = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        texto_diagrama = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblGannt = new javax.swing.JTable();
        lblCPUInfo = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProcesos = new javax.swing.JTable();
        lblRafaga = new javax.swing.JLabel();
        cpu_nuevo1 = new javax.swing.JLabel();
        lblRafagaEjecutada = new javax.swing.JLabel();
        tiempo_cpu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto_listos = new javax.swing.JTextArea();
        btnInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setFocusTraversalPolicyProvider(true);
        setForeground(new java.awt.Color(204, 255, 204));
        setLocation(new java.awt.Point(0, 0));
        pack();

        pnlArriba.setBackground(new java.awt.Color(193, 204, 235));
        pnlArriba.setLayout(null);

        lblBienvenida.setBackground(new java.awt.Color(204, 204, 204));
        lblBienvenida.setFont(new java.awt.Font("Centaur", 1, 50)); // NOI18N
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setText("SJF");
        pnlArriba.add(lblBienvenida);
        lblBienvenida.setBounds(0, 10, 1030, 40);

        btnIniciar.setBackground(new java.awt.Color(204, 255, 204));
        btnIniciar.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar(evt);
            }
        });
        pnlArriba.add(btnIniciar);
        btnIniciar.setBounds(550, 100, 150, 25);

        btnInsertar.setBackground(new java.awt.Color(204, 255, 204));
        btnInsertar.setFont(new java.awt.Font("Centaur", 1, 11)); // NOI18N
        btnInsertar.setText("INSERTAR");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar(evt);
            }
        });
        pnlArriba.add(btnInsertar);
        btnInsertar.setBounds(550, 70, 150, 23);

        btnPausar.setBackground(new java.awt.Color(204, 255, 204));
        btnPausar.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        btnPausar.setText("DETENER");
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausar(evt);
            }
        });
        pnlArriba.add(btnPausar);
        btnPausar.setBounds(550, 130, 150, 25);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        lblNumeroProcesos.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblNumeroProcesos.setText("Número de procesos:");
        jPanel2.add(lblNumeroProcesos);
        lblNumeroProcesos.setBounds(10, 30, 122, 16);

        procesos_en_ejecucion.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        procesos_en_ejecucion.setText("0");
        jPanel2.add(procesos_en_ejecucion);
        procesos_en_ejecucion.setBounds(150, 50, 41, 16);

        total_listos.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        total_listos.setText("0");
        jPanel2.add(total_listos);
        total_listos.setBounds(150, 30, 31, 16);

        lblEnEjecucion.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblEnEjecucion.setText("Proceso en ejecucion: ");
        jPanel2.add(lblEnEjecucion);
        lblEnEjecucion.setBounds(10, 50, 140, 16);

        tiempo_real.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        tiempo_real.setText("0");
        jPanel2.add(tiempo_real);
        tiempo_real.setBounds(150, 10, 24, 16);

        lblTiempoTotal.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblTiempoTotal.setText("Tiempo Total:");
        jPanel2.add(lblTiempoTotal);
        lblTiempoTotal.setBounds(10, 10, 122, 16);

        pnlArriba.add(jPanel2);
        jPanel2.setBounds(540, 180, 170,75);

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 0));
        txaConsola.setBackground(new java.awt.Color(204, 255, 204));
        //txaConsola.setBounds(730, 70, 260, 255);
        txaConsola.setFont(new java.awt.Font("Centaur", 1, 11));
        pnlArriba.add(txaConsola);        
        jScrollPane8.setViewportView(txaConsola);
        pnlArriba.add(jScrollPane8);
        jScrollPane8.setBounds(730, 70, 260, 255);

        lblFinalizados.setBackground(new java.awt.Color(255, 255, 0));
        lblFinalizados.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblFinalizados.setText("Procesos terminados");
        pnlArriba.add(lblFinalizados);
        lblFinalizados.setBounds(540, 215, 280, 100);

        jScrollPane6.setBackground(new java.awt.Color(255, 255, 0));

        texto_diagrama.setEditable(false);
        texto_diagrama.setColumns(20);
        texto_diagrama.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        texto_diagrama.setRows(5);        
        jScrollPane6.setViewportView(texto_diagrama);

        pnlArriba.add(jScrollPane6);
        jScrollPane6.setBounds(540, 275, 180, 60);

        jScrollPane7.setToolTipText("");

        tblGannt.setAutoCreateRowSorter(true);
        tblGannt.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        tblGannt.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {"1", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"2", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"3", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"4", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"5", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"6", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"7", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"8", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"9", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"10", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"11", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"12", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"13", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"14", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"15", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"16", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"17", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"18", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"19", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"20", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"21", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"22", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"23", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"24", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {"P25", null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
                },
                new String[]{
                    "P", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "TE", "TR"
                }
        ));
        tblGannt.setToolTipText("");
        tblGannt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblGannt.setColumnSelectionAllowed(true);
        tblGannt.setMaximumSize(new java.awt.Dimension(800, 416));
        tblGannt.setMinimumSize(new java.awt.Dimension(800, 416));
        tblGannt.setPreferredSize(new java.awt.Dimension(2200, 416));
        jScrollPane7.setViewportView(tblGannt);
        tblGannt.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        pnlArriba.add(jScrollPane7);
        jScrollPane7.setBounds(20, 340, 980, 200);

        lblCPUInfo.setBackground(new java.awt.Color(0, 0, 255));
        lblCPUInfo.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblCPUInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información de Ejecución", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pnlArriba.add(lblCPUInfo);
        lblCPUInfo.setBounds(530, 160, 190, 130);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(469, 416));

        jTableProcesos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTableProcesos.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        jTableProcesos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "Proceso", "T. Llegada", "T. Ráfaga", "T. Ejecucion", "T. Final", "T. Retorno", "T. Espera", "Prioridad"
                }
        ));

        jTableProcesos.setEnabled(false);
        jTableProcesos.setMaximumSize(new java.awt.Dimension(2147483647, 130));
        jTableProcesos.setMinimumSize(new java.awt.Dimension(750, 130));
        jScrollPane3.setViewportView(jTableProcesos);

        pnlArriba.add(jScrollPane3);
        jScrollPane3.setBounds(20, 70, 500, 260);

        lblRafaga.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblRafaga.setText("Tiempo ráfaga proceso:");
        pnlArriba.add(lblRafaga);
        lblRafaga.setBounds(770, 540, 135, 16);

        cpu_nuevo1.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        cpu_nuevo1.setText("0");
        pnlArriba.add(cpu_nuevo1);
        cpu_nuevo1.setBounds(930, 540, 62, 14);

        lblRafagaEjecutada.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        lblRafagaEjecutada.setText("Ráfaga ejecutada: ");
        pnlArriba.add(lblRafagaEjecutada);
        lblRafagaEjecutada.setBounds(580, 540, 105, 16);

        tiempo_cpu.setFont(new java.awt.Font("Centaur", 1, 12)); // NOI18N
        tiempo_cpu.setText("0");
        pnlArriba.add(tiempo_cpu);
        tiempo_cpu.setBounds(700, 540, 63, 20);

        texto_listos.setBackground(new java.awt.Color(0, 0, 0));
        texto_listos.setColumns(20);
        texto_listos.setForeground(new java.awt.Color(255, 255, 255));
        texto_listos.setRows(5);
        jScrollPane1.setViewportView(texto_listos);

        pnlArriba.add(jScrollPane1);
        jScrollPane1.setBounds(20, 540, 130, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlArriba, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

    }// </editor-fold>                        

    private void btnSeguir(java.awt.event.ActionEvent evt) {
        sjf.resume();
        btnPausar.setEnabled(true);

    }

    private void btnPausar(java.awt.event.ActionEvent evt) {

        sjf.stop();
        btnIniciar.setEnabled(true);
    }

    private void btnIniciar(java.awt.event.ActionEvent evt) {
        Cola cola = new Cola(txaConsola);
        cola = vProceso.getCola();
        sjf = new SJF(cola, this);
        sjf.start();
        btnIniciar.setEnabled(false);
        btnPausar.setEnabled(true);
    }

    private void btnInsertar(java.awt.event.ActionEvent evt) {
        vProceso.setVisible(true);
        btnIniciar.setEnabled(true);
    }

    // Variables declaration - do not modify  
    private JTextArea txaConsola;
    private javax.swing.JLabel cpu_nuevo1;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JLabel lblBienvenida;

    private javax.swing.JLabel lblFinalizados;
    private javax.swing.JLabel lblCPUInfo;
    private javax.swing.JLabel lblTiempoTotal;
    private javax.swing.JLabel lblEnEjecucion;
    private javax.swing.JLabel lblRafaga;
    private javax.swing.JLabel lblRafagaEjecutada;
    private javax.swing.JLabel lblNumeroProcesos;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel pnlArriba;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable tblGannt;
    private javax.swing.JTable jTableProcesos;
    private javax.swing.JLabel procesos_en_ejecucion;
    private javax.swing.JTextArea texto_diagrama;
    private javax.swing.JTextArea texto_listos;
    private javax.swing.JLabel tiempo_cpu;
    private javax.swing.JLabel tiempo_real;

    private javax.swing.JLabel total_listos;
    private javax.swing.JButton btnInsertar;
    // End of variables declaration  

    public JTextArea getTxaConsola() {
        return txaConsola;
    }

    public void setTxaConsola(JTextArea txaConsola) {
        this.txaConsola = txaConsola;
    }
    
    

}
